version: '3'

services:
  web:
    image: nginx:alpine
    container_name: example-webapp
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=ryuko-matoi.co
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ryuko-matoi.co
      - LETSENCRYPT_EMAIL=flavio.espinoza@gmail.com
    restart: always

networks:
  default:
    external:
      name: nginx-proxy